services:
  backend:
    build: ./backend
    container_name: analise-backend
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - selenium
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: analise-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge